# Generated by Django 5.2 on 2025-05-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPersonsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('alt1_dob', models.DateField(blank=True, null=True)),
                ('alt2_dob', models.DateField(blank=True, null=True)),
                ('alt3_dob', models.DateField(blank=True, null=True)),
                ('aka1_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('aka2_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('aka3_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personal address',
                'verbose_name_plural': 'Personal addresses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('home_addresses', models.ManyToManyField(related_name='persons', to='base.personaddress')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['id', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('alt1_dob', models.DateField(blank=True, null=True)),
                ('alt2_dob', models.DateField(blank=True, null=True)),
                ('alt3_dob', models.DateField(blank=True, null=True)),
                ('aka1_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('aka2_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('aka3_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_datas', to='base.person')),
            ],
            options={
                'verbose_name': 'Personal entry',
                'verbose_name_plural': 'Personal data',
            },
        ),
    ]
