# Generated by Django 5.2 on 2025-05-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'middle_name', 'ssn')},
        ),
        migrations.AlterUniqueTogether(
            name='personaddress',
            unique_together={('address', 'city', 'county', 'state', 'zip_code', 'phone')},
        ),
    ]
