# Generated by Django 5.2 on 2025-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_first_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allpersonsdata',
            index=models.Index(fields=['first_name', 'last_name', 'middle_name', 'ssn'], name='base_allper_first_n_d685f8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name', 'middle_name', 'ssn'], name='base_person_first_n_682f7d_idx'),
        ),
    ]
