# Generated by Django 5.2 on 2025-07-16 19:39

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_allpersonsdata_base_allper_first_n_d685f8_idx_and_more'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='trgm_idx_first_name', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='trgm_idx_last_name', opclasses=['gin_trgm_ops']),
        ),
    ]
