# Generated by Django 5.2 on 2025-07-16 23:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_person_trgm_idx_first_name_person_trgm_idx_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personaddress',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address'], name='trgm_idx_address', opclasses=['gin_trgm_ops']),
        ),
    ]
