# Generated by Django 5.2 on 2025-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_allpersonsdataatt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpersonsdataatt',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
