# Generated by Django 5.2 on 2025-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_allpersonsdataatt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpersonsdataatt',
            name='hash_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hash_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
