# Generated by Django 5.2 on 2025-07-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_allpersonsdataatt_hash_key_person_hash_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpersonsdataatt',
            name='hash_key',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hash_key',
        ),
    ]
